import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import { projects } from '@/fake-api/projects';

import Head from 'next/head';
import Skill from '@/components/styles/Skill';
import Container from '@/components/utils/Container';
import DownloadButton from '@/components/links/DownloadButton';
import Img from '@/components/utils/Img';
import SocialMedia from '@/components/styles/SocialMedia';
import Carousel from '@/components/styles/Carousel';

import image from '@/assets/home/program.svg';
import me from '@/assets/home/me.jpg';

const inter = Inter({ subsets: ['latin'], weight: ['400', '700'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>André Siboli | Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`} id="home">
                <Container>
                    <div className={styles.main_container}>
                        <div className={styles.main_info}>
                            <div className={styles.info}>
                                <div className={styles.info_title}>
                                    <h1>
                                        What&apos;s up? I&apos;m
                                        <div className={styles.words}>
                                            <span>Size</span>
                                            <span>André Siboli.</span>
                                            <span>Web Developer.</span>
                                        </div>
                                    </h1>
                                </div>
                                <div className={styles.info_description}>
                                    <p>
                                        If you&apos;re looking for a web developer who&apos;s
                                        passionate, skilled, and committed to making your online
                                        vision a reality, you&apos;ve come to the right place.
                                        Let&apos;s connect and turn your ideas into a web presence
                                        that truly stands out.
                                    </p>
                                </div>
                                <div className={styles.info_download}>
                                    <DownloadButton
                                        archive={'./curriculo.pdf'}
                                        content="Download my CV"
                                    />
                                </div>
                            </div>
                        </div>
                        <div className={styles.main_image}>
                            <div className={styles.image}>
                                <Img src={image} style={{ objectFit: 'cover' }} />
                            </div>
                        </div>
                    </div>
                </Container>
            </main>

            <section className={`${styles.about} ${inter.className}`} id="about">
                <Container>
                    <div className={styles.about_container}>
                        <div className={styles.about_image}>
                            <div className={styles.card}>
                                <div className={styles.card_image}>
                                    <Img
                                        src={me}
                                        style={{ objectFit: 'cover', objectPosition: 'center 20%' }}
                                    />
                                </div>
                                <div className={styles.card_social}>
                                    <SocialMedia style={{ color: '#fff' }} />
                                </div>
                            </div>
                        </div>
                        <div className={styles.about_info}>
                            <div className={styles.info_title}>
                                <h2>About me</h2>
                            </div>

                            <div className={styles.info_content}>
                                <span>Web Developer</span>
                                <p>
                                    What&apos;s up? My name is André Siboli. I was born and live in
                                    Brazil. I graduated in Information Technology from Universidade
                                    Cruzeiro do Sul. I&apos;ve always been interested in programming
                                    since I was a child. I love this world and how a simple line of
                                    code can change lives. For me, web development is a blend of art
                                    and technology, where every line of code is a stroke on the
                                    canvas of the digital world.
                                </p>
                            </div>
                        </div>
                    </div>
                </Container>
            </section>

            <section className={`${styles.skills} ${inter.className}`} id="skills">
                <Container>
                    <div className={styles.skills_container}>
                        <div className={styles.skills_title}>
                            <h2>Skills</h2>
                        </div>
                        <div className={styles.skills_skills}>
                            <div className={styles.skills_group}>
                                <Skill name="HTML5" percent={90} />
                                <Skill name="CSS3/SASS" percent={80} />
                                <Skill name="React/NextJs" percent={75} />
                                <Skill name="Typescript" percent={75} />
                            </div>
                            <div className={styles.skills_group}>
                                <Skill name="NodeJs" percent={55} />
                                <Skill name="Git/GitHub" percent={70} />
                                <Skill name="MySQL/MongoDb" percent={70} />
                                <Skill name="English" percent={60} />
                            </div>
                        </div>
                    </div>
                </Container>
            </section>
            <section className={`${styles.projects} ${inter.className}`} id="projects">
                <Container>
                    <div className={styles.projects_container}>
                        <div className={styles.projects_title}>
                            <h2>Projects</h2>
                        </div>
                        <div className={styles.project_carousel}>
                            <Carousel datas={projects} />
                        </div>
                    </div>
                </Container>
            </section>
        </>
    );
}
